spring:
  profiles:
    active: dev  # 激活开发环境配置
---
server:
  port: 9527
spring:
  profiles:
    active: dev  # 激活开发环境配置
  application:
    name: microservice-config-dev
---
server:
  port: 9528
spring:
  profiles:
    active: prod  # 激活开发环境配置
  application:
    name: microservice-config-prod